"""Data access layer: one module per domain, re-exported as a facade.

Every function takes the DuckDB connection as its first argument and returns
pydantic models from :mod:`website.models`.
"""

from website.repository._rows import IntegrityError
from website.repository.users import (
    get_user_by_username,
    get_user_by_id,
    create_user,
)
from website.repository.posts import (
    list_posts,
    get_post_by_id,
    create_post,
    update_post,
    delete_post,
)
from website.repository.seasons import (
    list_seasons,
    get_season_by_id,
    create_season,
    delete_season,
)
from website.repository.fixtures import (
    count_fixtures_for_season,
    list_fixtures_for_season,
    list_fixture_dates,
    get_fixture_by_id,
    create_fixture,
    update_fixture,
    delete_fixture,
    set_fixture_source_pdf,
    list_fixture_images,
    get_fixture_image_by_id,
    create_fixture_image,
    delete_fixture_image,
)
from website.repository.results import (
    race_sort_key,
    list_races_for_fixture,
    get_race_by_id,
    create_race,
    list_results_for_race,
    fixture_has_results,
    create_result,
)
from website.repository.standings import (
    load_individual_standings,
    load_team_standings,
    list_standing_categories,
    season_has_standings,
    replace_calculated_individual_standings,
    replace_calculated_team_standings,
)
from website.repository.pages import (
    get_static_page,
    upsert_static_page,
)
from website.repository.administration import (
    list_administration_sections,
    get_administration_section,
    create_administration_section,
    delete_administration_section,
    create_administration_document,
    delete_administration_document,
)
from website.repository.clubs import (
    list_clubs,
    list_public_clubs,
    get_club_by_id,
    create_club,
    update_club,
    toggle_club_active,
    club_has_active_batches,
    list_club_managers,
    get_club_for_manager,
    create_club_manager,
    get_club_manager_email,
    toggle_club_manager_active,
)
from website.repository.links import (
    list_external_links,
    get_external_link,
    create_external_link,
    update_external_link,
    toggle_external_link,
    delete_external_link,
)
from website.repository.divisions import (
    list_division_assignments,
    get_division_assignment,
    create_division_assignment,
    update_division_assignment,
    delete_division_assignment,
)
from website.repository.winners import (
    list_winner_overrides,
    get_winner_override,
    create_winner_override,
    update_winner_override,
    delete_winner_override,
    toggle_winner_override,
    list_public_winners,
)
from website.repository.entries import (
    get_season_entry_config,
    upsert_season_entry_config,
    create_entry_batch,
    get_entry_batch,
    get_entry_batch_by_stripe_session,
    update_batch_status,
    set_batch_stripe_session,
    list_entry_batches_for_season,
)
from website.repository.athlete_entries import (
    get_entered_ea_urns,
    create_athlete_entries,
    get_athlete_entries_for_batch,
    list_athlete_entries_for_season,
    assign_race_numbers,
    update_athlete_race_number,
    upsert_club_allocation,
    get_club_allocation,
    get_club_athlete_count,
    list_club_allocations_for_season,
    list_paid_athlete_entries_for_season,
)

__all__ = [
    "IntegrityError",
    "assign_race_numbers",
    "club_has_active_batches",
    "count_fixtures_for_season",
    "create_administration_document",
    "create_administration_section",
    "create_athlete_entries",
    "create_club",
    "create_club_manager",
    "create_division_assignment",
    "create_entry_batch",
    "create_external_link",
    "create_fixture",
    "create_fixture_image",
    "create_post",
    "create_race",
    "create_result",
    "create_season",
    "create_user",
    "create_winner_override",
    "delete_administration_document",
    "delete_administration_section",
    "delete_division_assignment",
    "delete_external_link",
    "delete_fixture",
    "delete_fixture_image",
    "delete_post",
    "delete_season",
    "delete_winner_override",
    "fixture_has_results",
    "get_administration_section",
    "get_athlete_entries_for_batch",
    "get_club_allocation",
    "get_club_athlete_count",
    "get_club_by_id",
    "get_club_for_manager",
    "get_club_manager_email",
    "get_division_assignment",
    "get_entered_ea_urns",
    "get_entry_batch",
    "get_entry_batch_by_stripe_session",
    "get_external_link",
    "get_fixture_by_id",
    "get_fixture_image_by_id",
    "get_post_by_id",
    "get_race_by_id",
    "get_season_by_id",
    "get_season_entry_config",
    "get_static_page",
    "get_user_by_id",
    "get_user_by_username",
    "get_winner_override",
    "list_administration_sections",
    "list_athlete_entries_for_season",
    "list_club_allocations_for_season",
    "list_club_managers",
    "list_clubs",
    "list_division_assignments",
    "list_entry_batches_for_season",
    "list_external_links",
    "list_fixture_dates",
    "list_fixture_images",
    "list_fixtures_for_season",
    "list_paid_athlete_entries_for_season",
    "list_posts",
    "list_public_clubs",
    "list_public_winners",
    "list_races_for_fixture",
    "list_results_for_race",
    "list_seasons",
    "list_standing_categories",
    "list_winner_overrides",
    "load_individual_standings",
    "load_team_standings",
    "race_sort_key",
    "replace_calculated_individual_standings",
    "replace_calculated_team_standings",
    "season_has_standings",
    "set_batch_stripe_session",
    "set_fixture_source_pdf",
    "toggle_club_active",
    "toggle_club_manager_active",
    "toggle_external_link",
    "toggle_winner_override",
    "update_athlete_race_number",
    "update_batch_status",
    "update_club",
    "update_division_assignment",
    "update_external_link",
    "update_fixture",
    "update_post",
    "update_winner_override",
    "upsert_club_allocation",
    "upsert_season_entry_config",
    "upsert_static_page",
]
